# See https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration

server:
  port: 8080
logging:
  file: flow.log
  level:
    com:
       checkmarx:
          flow:
             cmd: TRACE
             service: TRACE
             controller: TRACE
    org:
       apache:
          http:
             wire: TRACE
       springframework:
          web:
             client:
                RestTemplate: TRACE

cxflow:
  bug-tracker: GitLab
  bug-tracker-impl:
    - GitLab
  branches:
  - master
  - main
  - merge_request
  filter-severity:
  # - High
  filter-category:
  #- SQL_Injection
  #- Stored_XSS
  #- Reflected_XSS_All_Clients
  filter-cwe:
  filter-status:
  # - Urgent
  # - Confirmed
  # - To Verify
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  #wiki-url: https://custodela.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://cimpress.codebashing.com/
  enabled-vulnerability-scanners:
    - sast
    #- sca
  profiling-depth: 3

checkmarx:
  version: 9.0
  username: 
  password: 
  client-id: resource_owner_client
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  scope: access_control_api sast_rest_api
  base-url: https://cimpress.checkmarx.net
  multi-tenant: true
  configuration: Default Configuration
  preserve-xml: true
  team: 
  url: ${checkmarx.base-url}/cxrestapi
  scan-preset: Checkmarx Default
  incremental: true
  # settings-override, default is false if not provided, See: https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#override-project-settings
  settings-override: true
  #WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl

gitlab:
  webhook-token: 
  token: 
  url: https://gitlab.com
  api-url: https://gitlab.com/api/v4
  false-positive-label: false-positive
  block-merge: false
  cx-summary: true
